version: '2.4'
services:
  app:
    image: ocd-api
    container_name: ocd-api
    restart: always
    build: .
    stdin_open: true
    tty: true
    ports:
      - 8011:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - ${PWD}/configs/settings_local.py:/app/ocdapi/settings_local.py
    environment:
      POSTGRES_HOST: postgres
      DJANGO_MANAGEPY_MIGRATE: "on"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: ocd-api-postgres
    restart: always
    image: mdillon/postgis:9.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: opencivicdata
    volumes:
      - ocd-api-db-data:/var/lib/postgresql/data
    ports:
      - 32005:5432

volumes:
  ocd-api-db-data:
