version: '2.4'
services:

  postgres:
    container_name: ocd-api-postgres
    restart: always
    image: mdillon/postgis:9.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: opencivicdata
    volumes:
      - ocd-api-db-data:/var/lib/postgresql/data
    ports:
      - 32005:5432

volumes:
  ocd-api-db-data:
