# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 10:49
from __future__ import unicode_literals
import re

from django.db import migrations
from opencivicdata.legislative.models import Bill

class Migration(migrations.Migration):
    def unmangle_identifier(apps, schema_editor):
        '''
        The `fix_bill_id` function mangled NYC Bills in at least two ways:
        (1) removing zeroes, e.g., 'Res 0229-2004' (original) becomes 'Res 229-2004' (mangled)
        (2) adding a space, e.g., 'T2018-1245' (original) becomes 'T 2018-1245' (mangled).

        Note: the second case ONLY affected bills that begin with 'T', and the first case did NOT affect bills that begin with 'T' - that is, NYC bills never follow these patterns 'T 0023-2015' or 'T0023-2015'.
        '''

        nyc_bills = Bill.objects.filter(from_organization__jurisdiction__id='ocd-jurisdiction/country:us/state:ny/place:new_york/government')

        deleted_zeroes = r'^([A-Za-z]*\s)(\d{1,3})(-\d{4})$'
        for bill in nyc_bills.filter(identifier__iregex=deleted_zeroes):
            pattern = re.compile(deleted_zeroes)
            unmangled_identifier = pattern.sub(lambda match: match.group(1) + '{:0>4}'.format(match.group(2)) + match.group(3), bill.identifier)

            bill.identifier = unmangled_identifier
            bill.save()

        added_space = r'^([T]*\s)(\d{1,4}-\d{1,4})$'
        for bill in nyc_bills.filter(identifier__iregex=added_space):
            print("***")
            print(bill.identifier)
            pattern = re.compile(added_space)
            unmangled_identifier = pattern.sub(lambda match: match.group(1).rstrip() + match.group(2), bill.identifier)

            print(unmangled_identifier)
            bill.identifier = unmangled_identifier
            bill.save()

    dependencies = [
    ]

    operations = [
        migrations.RunPython(unmangle_identifier)
    ]
