# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 14:29
from __future__ import unicode_literals
import re

from django.db import migrations
from opencivicdata.legislative.models import Bill

class Migration(migrations.Migration):
    def unmangle_identifier(apps, schema_editor):
        '''
        The `fix_bill_id` function mangled nearly all Chicago bill identifiers by adding a space, e.g., 'R2010-1185' (original) vs. 'R 2010-1185' (mangled).

        This migration unmangles identifiers. 
        '''

        print('Running CHICAGO MIGRATION')

        added_space = r'^([A-Za-z]+)\s([-\d]+)$'

        chicago_bills = Bill.objects.filter(from_organization__jurisdiction__id='ocd-jurisdiction/country:us/state:il/place:chicago/government').filter(identifier__iregex=added_space)

        for bill in chicago_bills:
            match = re.match(added_space, bill.identifier)
            unmangled_identifier = '{mangled_prefix}{count}'.format(mangled_prefix=match.group(1), 
                                                                    count=match.group(2))

            print('{} becomes {}'.format(bill.identifier, unmangled_identifier))
            try:
                duplicate = Bill.objects.get(identifier=unmangled_identifier)
                print('{} - duplicate found. Deleting.'.format(unmangled_identifier))
                duplicate.delete()
            except Bill.DoesNotExist: 
                pass

            bill.identifier = unmangled_identifier
            bill.save()

    dependencies = [
        ('ocdapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(unmangle_identifier)
    ]
